
/* We first check whether the required elements exist on the webpage. If they
 * do not, it means that either the user is looking at something other than
 * a project page, or that github changed their layout and we need to adapt
 * this code. Either way, this ensures that no errors are generated by this
 * extension due to missing DOM elements. */
var el = window.document.querySelector('h1.entry-title strong a.js-repo-home-link');
if (el) { insertStatusIcon(el); }


/* The status icon may not exist, if the project is not registered on
 * travis-ci.org. So we first create the img element and see if an error
 * happens while loading this image. Only if the image exists, we insert the
 * icon into the DOM. */
function insertStatusIcon(el) {
    var project = el.pathname;


    var img = window.document.createElement('img');
    img.src = 'https://secure.travis-ci.org' + project + '.png';
    img.alt = 'build status'


    /* When the image is loaded, we insert it into the DOM. This event is only
     * fired if the image was loaded successfully, it will not fire if the
     * image does not exist. */
    img.onload = function() {
        /* Add relevant rules to the stylesheet. */
        document.styleSheets[0].insertRule('#travis-ci{border-radius:1px;display:inline-block;margin-left:8px;margin-bottom:-1px;opacity:0.9;-webkit-transition: all .2s;}', 1)
        document.styleSheets[0].insertRule('#travis-ci:hover{background:rgba(0,0,0,0.5);box-shadow: 0 0 3px rgba(0,0,0,1);opacity:1;cursor:pointer;}', 1)
        document.styleSheets[0].insertRule('#travis-ci img{display:block;}', 1)


        /* Create the link element. */
        var link = window.document.createElement('a');
        link.href = 'http://travis-ci.org' + project;
        link.id = 'travis-ci';

        /* And finally insert the elements into the DOM. */
        link.appendChild(img);
        el.appendChild(link);
    }
}
